Feature/devise gem
zainsadaqat/blog-app pull request #9
Opened 2022-03-03 21:48 UTC by zainsadaqat

## In this pull request, I've done the following:

- Add `devise` gem
- `Sign in` feature
- `Log out` feature
- `Register` new user
- `Fix linters`

<img src="https://media1.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif"/>

2022-03-03 22:59 UTC, andersonlebon requested changes
## Hi @zainsadaqat 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-03 22:59 UTC, andersonlebon commented on db/migrate/20220303010407_add_name_to_users.rb
> +end
- [x] Kindly Make sure you don't have duplicated migration. Currently, you have many migrations that are throwing errors when running migrations. I was able to identify them and these ones I reminded with :point_down: 

![image](https://user-images.githubusercontent.com/65068771/156665260-dd292d9f-4256-4b7c-9ef6-6faac1c6bb6a.png)

2022-03-03 22:59 UTC, andersonlebon commented on db/migrate/20220302232643_devise_create_users.rb
> +
- [x] This migration will create a user table but remember you created a user table before. Kindly remove the previous migration that created the user table because this devise migration will create it.

- [x] Also you need to use Make this migration to be the first migration so that you may not get errors saying `PG::UndefinedTable: ERROR:  relation "users" does not exist`

2022-03-03 22:59 UTC, andersonlebon commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
- [x] As the requirements say Kindly you should allow the user the get a confirmation(`:confirmable`) after the user has signed up :point_down: 

```ruby
devise :database_authenticatable, :registerable,
				:recoverable, :rememberable, :validatable, :confirmable
```

2022-03-04 10:51 UTC, zainsadaqat commented on db/migrate/20220302232643_devise_create_users.rb
> +
I have deleted all the duplicated migrations. now it's working fine. ✅

2022-03-04 11:24 UTC, zainsadaqat commented on db/migrate/20220303010407_add_name_to_users.rb
> +end
✅

2022-03-04 16:38 UTC, zainsadaqat commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
Successfully added the confirmation feature

2022-03-04 16:53 UTC, descholar-ceo approved these changes
Hi @zainsadaqat , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-04 17:32 UTC, merged

2022-03-04 17:33 UTC, zainsadaqat commented
Thanks @descholar-ceo for approving this Pull Request!